name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses:

  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.59

      - uses: tschm/cradle/actions/deptry@v0.1.59
        with:
          source-folder: prompting
