name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: tschm/cradle/actions/pre-commit@v0.3.04

  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.3.04

      - uses: tschm/cradle/actions/deptry@v0.3.04
        with:
          source-folder: prompting
